Select * from customer;

--Q1. What is the total revenue generated by male vs. female customers?
Select gender, sum(purchse_amount) from customer group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select customer_id, purchse_amount, discount_applied from customer
where (discount_applied = 'Yes') 
and purchse_amount >= (Select avg(purchse_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased, round(avg(review_rating)::numeric,2) as average_rating from customer
group by item_purchased
order by average_rating desc limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
Select shipping_type, round(avg(purchse_amount),2) from customer
where shipping_type in ('Express','Standard')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
Select subscription_status,count(*) as no_of_customer,
round(avg(purchse_amount),2) as avg_amount,
sum(purchse_amount) as total_amount from customer
group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased, 
round(100 * sum(case when (discount_applied = 'Yes') Then 1 Else 0 End) / count(*),2) 
as discountapplied from customer group by item_purchased
order by discountapplied desc limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as(
Select customer_id, previous_purchases,
case 
	when previous_purchases = 1 Then 'New'
	when previous_purchases Between 2 and 10 Then 'Returning'
	else 'Loyal' end as customer_segement
	from customer
)

Select customer_segement, count(*) as no_of_customer from customer_type 
group by customer_segement
order by no_of_customer desc;

--Q8. What are the top 3 most purchased products within each category? 
with item_counts as(
Select category, item_purchased, count(*) as total_orders,
Row_Number() over(partition by category order by count(*)) as item_rank
from customer
group by category, item_purchased
)

Select * from item_counts
where item_rank<=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status, count(*) as no_of_customer from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
Select age_groups, sum(purchse_amount) as revenue from customer
group by age_groups
order by revenue desc;